export const cloudPlans = [
  {
    name: "Founder",
    price: 49,
    annualPrice: 439,
    highlight: false,
    desc: "Ideal para productoras que quieren empezar con Streamrace en un esquema de acceso limitado.",
    features: [
      "Branding de Streamrace",
      "Varios diseños de gráficas",
      "Setup guiado",
      "Base de datos",
      "Funciones online",
      "Soporte con el desarrollador",
      "Cupos limitados",
      "Hasta 3 eventos por año",
    ],
    cta: "Elegir plan",
    type: "demo",
    badge: "",
  },
  {
    name: "Pro",
    price: 79,
    annualPrice: 699,
    highlight: false,
    desc: "Pensado para productoras que necesitan operar con su propia marca y más de una instancia en simultáneo.",
    features: [
      "Branding de productora",
      "Powered by Streamrace",
      "Varios diseños de gráficas",
      "Setup guiado",
      "Base de datos",
      "Funciones online",
      "Soporte estándar",
      "2 instancias simultáneas",
    ],
    cta: "Elegir plan",
    type: "demo",
    badge: "",
  },
  {
    name: "Premium",
    price: 129,
    annualPrice: 1199,
    highlight: true,
    desc: "Recomendado para productoras que necesitan más capacidad operativa, respuesta prioritaria y una implementación más sólida.",
    features: [
      "Branding de productora",
      "Powered by Streamrace",
      "Varios diseños de gráficas",
      "Setup guiado",
      "Base de datos",
      "Funciones online",
      "Soporte prioritario",
      "Hasta 3 instancias simultáneas",
    ],
    cta: "Elegir plan",
    type: "demo",
    badge: "",
  },
  {
    name: "Studio",
    price: null,
    highlight: false,
    desc: "Para organizaciones que necesitan marca blanca, personalización a medida y una propuesta comercial más avanzada.",
    features: [
      "Personalización del diseño a medida",
      "Todas las funciones de Streamrace",
      "Base de datos",
      "Funciones online",
      "Múltiples instancias simultáneas",
      "Soporte prioritario",
    ],
    cta: "Hablar con ventas",
    type: "demo",
    badge: "",
  },
];

export const desktopPlans = [
  {
    licenses: 1,
    price: 1490,
    unitPrice: 1490,
    highlight: false,
    desc: "Ideal para operación local en una estación de trabajo, con licencia perpetua y funcionamiento offline.",
    features: [
      "Licencia perpetua",
      "Funcionamiento 100% offline",
      "12 meses de actualizaciones",
      "Instalación y configuración inicial",
    ],
    cta: "Solicitar Licencia",
    type: "desktop",
    badge: "",
  },
  {
    licenses: 2,
    price: 2380,
    unitPrice: 1190,
    highlight: false,
    desc: "Pensado para organizaciones que necesitan redundancia o una segunda estación operativa con licencia perpetua.",
    features: [
      "Licencia perpetua",
      "Funcionamiento 100% offline",
      "12 meses de actualizaciones",
      "Instalación y configuración inicial",
    ],
    cta: "Solicitar Licencia",
    type: "desktop",
    badge: "",
  },
  {
    licenses: 3,
    price: 2970,
    unitPrice: 990,
    highlight: true,
    desc: "Recomendado para operaciones con varias estaciones, mayor cobertura técnica y mejor costo por licencia.",
    features: [
      "Licencia perpetua",
      "Funcionamiento 100% offline",
      "12 meses de actualizaciones",
      "Instalación y configuración inicial",
    ],
    cta: "Solicitar Licencia",
    type: "desktop",
    badge: "",
  },
];

export const connectPlans = [
  {
    instances: 1,
    price: 29,
    highlight: false,
    desc: "Sumá funciones en linea a tu instalación local.",
    features: [
      "Votación por QR",
      "Clima automático",
      "Integración con Chat de YouTube",
      "Sincronización Cloud",
      "Futuras funciones online",
    ],
    cta: "Agregar Connect",
    type: "connect",
    badge: "✨ Amplía tu Licencia Desktop",
  },
  {
    instances: 2,
    price: 49,
    highlight: false,
    desc: "Sumá funciones en linea a tus instalaciónes locales.",
    features: [
      "Votación por QR",
      "Clima automático",
      "Integración con Chat de YouTube",
      "Sincronización Cloud",
      "Futuras funciones online",
    ],
    cta: "Agregar Connect",
    type: "connect",
    badge: "",
  },
  {
    instances: 3,
    price: 79,
    highlight: true,
    desc: "Sumá funciones en linea a tus instalaciónes locales.",
    features: [
      "Votación por QR",
      "Clima automático",
      "Integración con Chat de YouTube",
      "Sincronización Cloud",
      "Futuras funciones online",
    ],
    cta: "Agregar Connect",
    type: "connect",
    badge: "Amplía tu Licencia Desktop",
  },
];

export const formatCurrency = (value) =>
  `US$ ${value.toLocaleString("de-DE", { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
