export const cloudPlans = [
  {
    name: "Founder",
    price: 49,
    annualPrice: 439,
    highlight: false,
    desc: "Sistema Streamrace completo para socios fundadores.",
    features: [
      "Branding de Streamrace",
      "Varios Diseños de Gráficas",
      "Setup guiado",
      "Base de Datos",
      "Funciones Online",
      "Soporte con el desarrollador",
      "Cupos Limitados",
      "Eventos simultaneos hasta 3 por año.",
    ],
    cta: "Elegir plan",
    type: "demo",
    badge: "",
  },
  {
    name: "Pro",
    price: 79,
    annualPrice: 699,
    highlight: false,
    desc: "Sistema Streamrace completo.",
    features: [
      "Branding de Productora",
      "Powered by Streamrace",
      "Varios Diseños de Gráficas",
      "Setup guiado",
      "Base de Datos",
      "Funciones Online",
      "Soporte Standard",
      "2 instancias simultáneas",
    ],
    cta: "Elegir plan",
    type: "demo",
    badge: "",
  },
  {
    name: "Premium",
    price: 129,
    annualPrice: 1199,
    highlight: true,
    desc: "Sistema Streamrace completo.",
    features: [
      "Branding de Productora",
      "Powered by Streamrace",
      "Varios Diseños de Gráficas",
      "Setup guiado",
      "Base de Datos",
      "Funciones Online",
      "Soporte prioritario",
      "Hasta 3 instancias simultáneas",
      "Soporte prioritario",
    ],
    cta: "Elegir plan",
    type: "demo",
    badge: "",
  },
  {
    name: "Studio",
    price: null,
    highlight: false,
    desc: "Streamrace completo con Marca Blanca.",
    features: [
      "Personalización del diseño a medida",
      "Todas las funciones de Streamrace",
      "Base de Datos",
      "Funciones Online",
      "Multiples instancias simultáneas",
      "Soporte prioritario",
    ],
    cta: "Hablar con ventas",
    type: "demo",
    badge: "",
  },
];

export const desktopPlans = [
  {
    licenses: 1,
    price: 1490,
    unitPrice: 1490,
    highlight: false,
    desc: "Streamrace Desktop para 1 dispositivo, Windows/macOS.",
    features: [
      "Licencia perpetua",
      "Funcionamiento 100% offline",
      "12 meses de actualizaciones",
      "Instalación y configuración inicial",
    ],
    cta: "Solicitar Licencia",
    type: "desktop",
    badge: "",
  },
  {
    licenses: 2,
    price: 2380,
    unitPrice: 1190,
    highlight: false,
    desc: "Streamrace Desktop para 2 dispositivos, Windows/macOS.",
    features: [
      "Licencia perpetua",
      "Funcionamiento 100% offline",
      "12 meses de actualizaciones",
      "Instalación y configuración inicial",
    ],
    cta: "Solicitar Licencia",
    type: "desktop",
    badge: "",
  },
  {
    licenses: 3,
    price: 2970,
    unitPrice: 990,
    highlight: true,
    desc: "Streamrace Desktop para 3 dispositivos, Windows/macOS.",
    features: [
      "Licencia perpetua",
      "Funcionamiento 100% offline",
      "12 meses de actualizaciones",
      "Instalación y configuración inicial",
    ],
    cta: "Solicitar Licencia",
    type: "desktop",
    badge: "",
  },
];

export const connectPlans = [
  {
    instances: 1,
    price: 29,
    highlight: false,
    desc: "Sumá funciones en linea a tu instalación local.",
    features: [
      "Votación por QR",
      "Clima automático",
      "Integración con Chat de YouTube",
      "Sincronización Cloud",
      "Futuras funciones online",
    ],
    cta: "Agregar Connect",
    type: "connect",
    badge: "✨ Amplía tu Licencia Desktop",
  },
  {
    instances: 2,
    price: 49,
    highlight: false,
    desc: "Sumá funciones en linea a tus instalaciónes locales.",
    features: [
      "Votación por QR",
      "Clima automático",
      "Integración con Chat de YouTube",
      "Sincronización Cloud",
      "Futuras funciones online",
    ],
    cta: "Agregar Connect",
    type: "connect",
    badge: "",
  },
  {
    instances: 3,
    price: 79,
    highlight: true,
    desc: "Sumá funciones en linea a tus instalaciónes locales.",
    features: [
      "Votación por QR",
      "Clima automático",
      "Integración con Chat de YouTube",
      "Sincronización Cloud",
      "Futuras funciones online",
    ],
    cta: "Agregar Connect",
    type: "connect",
    badge: "Amplía tu Licencia Desktop",
  },
];

export const formatCurrency = (value) =>
  `US$ ${value.toLocaleString("de-DE", { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
